/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_HelloWorld
#define _Included_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorld
 * Method:    chamarMensagem
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HelloWorld_chamarMensagem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     HelloWorld
 * Method:    dobro
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_HelloWorld_dobrar
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
